### ISSUE TITLE
Summarize data older than some relative time

### ISSUE THREAD

**Issue by dlmarion** [NationalSecurityAgency/timely#73]
Recent data could be very granular (seconds). This gets costly in terms of storage as we keep more data online. Provide the ability to summarize (count, min, avg, max) data points in a time series that are older than some configurable time period. The time window for summarization should also be configurable.

**Comment by klucar** [comment]
We really need to be careful about this because Count, Min, Max, Avg are usually really poor choices for summarizing data. I have been playing with the idea of "meta-metrics" for a bit and maybe that's the solution here. Meta-metrics would be these summarized metrics re-inserted as new metric names. Then we could just age-off the original metrics sooner. Not sure if this is a job for Timely or some other program though. One meta-metric that would be good to do is percentiles (50, 75, 90, 99, 999).

**Comment by brianloss** [comment]
[Dropwizard Metrics](http://metrics.dropwizard.io/) is a decent library I've used. It will let you collect metrics and does a statistical sampling (so you don't have to keep everything in memory) and from that you can then get min, max, average, std deviation, several percentiles (50, 75, 95, 98, 99, 999). Maybe in a combiner we could slurp in all of the metrics to be aged off and then spit out the desired stats as a new metric. That's a transformation, so we'd have to be careful with sort order from the Accumulo point of view.

**Comment by dlmarion** [comment]
> Maybe in a combiner we could slurp in all of the metrics to be aged off and then spit out the desired stats as a new metric.

I think ageoff and summarization are exclusive from one another. You might choose to summarize data for a metric older than 7 days, and age it off at 30 days.

**Comment by klucar** [comment]
The more I think about this, I think it might be best to do this outside of timely. Whatever decision we make, it won't be ideal for everyone. I'd rather see people run a summary report (some big query by a python script or map/reduce job or something) then re-insert that data as a new metric or a new tag on the same metric. This could make people make more dashboards, but perhaps some templating could help that situation.

**Comment by dlmarion** [comment]
Initial capability is working, closing.
