### ISSUE TITLE
Calculate rates before downsampling

### ISSUE THREAD

**Issue by klucar** [NationalSecurityAgency/timely#84]
For rate queries, we need to create a RateIterator/DerivativeIterator that calculates the difference between adjacent samples before the DownsampleIterator. Calculating the rate after the downsample, produces rates that depend on the downsample results. For example:

Raw data series:
0 1 2 3 4 5 6 7 8 9
Correct Rate:
1 1 1 1 1 1 1 1 1

Down sample series by 3:
    2    5   8
Down sampled rate:
 3 3

And it's worse if you downsample by summing.

**Comment by DRitch** [comment]
Don't forget that when calculating a rate, you need to divide by the number of seconds (or whatever time sample is used).

**Comment by klucar** [comment]
ah yes, but still I think this should be done before downsampling. A rate iterator essentially creates a new metric that we can act on like any other metric.

**Comment by DRitch** [comment]
The only difference between the results should be rounding error, and we're working with integers.  I would be quite surprised to see the difference between the two be significant.  It might make a difference with interpolation, but I would expect that to be minor.

In your example, the rate is constant 1 either way.

**Comment by dlmarion** [comment]
Instead of a new iterator, it might be easier to modify the existing downsample iterator. The downsample iterator calls [Downsample.add] (https://github.com/NationalSecurityAgency/timely/blob/master/server/src/main/java/timely/sample/Downsample.java#L57) to add the current K,V to a bucket using the configured aggregator (min, max, sum, etc). Could it be that we add a new aggregator called 'rate'? I'll look into it this week.
